export const fonts = {
    body: ({
        family: 'Montserrat',
        size: {
            xs: 12,
            sm: 15,
            md: 17,
            lg: 20,
            xl: 24,
            '2xl': 32,
            '3xl': 48,
            '4xl': 60,
            true: 15,
        },
        letterSpacing: {},
        weight: {
            normal: '400',
            medium: '500',
            semibold: '600',
            bold: '700',
        },
        lineHeight: {
            xs: 16,
            sm: 20,
            md: 24,
            lg: 28,
            xl: 32,
            '2xl': 40,
            '3xl': 58,
            '4xl': 70,
            true: 20,
        },
        face: {
            400: {normal: 'Montserrat'},
            500: {normal: 'MontserratMedium'},
            600: {normal: 'MontserratSemiBold'},
            700: {normal: 'MontserratBold'},
        },
    }),
    heading: ({
        family: 'Montserrat',
        size: {
            xs: 12,
            sm: 15,
            md: 17,
            lg: 20,
            xl: 24,
            '2xl': 32,
            '3xl': 48,
            '4xl': 60,
            true: 15,
        },
        letterSpacing: {},
        weight: {
            normal: '400',
            medium: '500',
            semibold: '600',
            bold: '700',
        },
        lineHeight: {
            xs: 16,
            sm: 20,
            md: 24,
            lg: 28,
            xl: 32,
            '2xl': 40,
            '3xl': 58,
            '4xl': 70,
            true: 20,
        },
        face: {
            400: {normal: 'Montserrat'},
            500: {normal: 'MontserratMedium'},
            600: {normal: 'MontserratSemiBold'},
            700: {normal: 'MontserratBold'},
        },
    }),
}